### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kozross** [jmcantrell/bashful#12]
What license are these wonderful libraries under?

**Comment by jmcantrell** [comment]
I didn't anticipate anyone finding these scripts useful. MIT is probably sufficient. Do you have a suggestion?

**Comment by kozross** [comment]
I'm a copyleft fan myself, but in reality, as long as it's one of the [free software licenses][1], anything's good.

[1]: https://www.gnu.org/licenses/license-list.html

**Comment by jmcantrell** [comment]
Just added GPLv3: https://github.com/jmcantrell/bashful/blob/master/LICENSE
