### ISSUE TITLE
Request: documentation in github

### ISSUE THREAD

**Issue by TechWiz-3** [jmcantrell/bashful#16]
**Request**
Could we get documentation in github as part of READMEs or a Wiki?
I find it easier to read documentation that way and I think people would find the project more appealing if they could read about the libraries functions before cloning.

**Comment by jmcantrell** [comment]
I've thought about this, too. It's been a long time since I've touched this project, and I'd like to update it with things I've learned.

**Comment by TechWiz-3** [comment]
Cool :)
